<#
    Rogologo — Windows install wizard
    -----------------------------------------------------------------
    Steps:
      1. Preflight (Docker, Node, Claude CLI)
      2. claude /login (subscription) — optional
      3. Collect Telegram & Slack tokens — optional
      4. Generate .env
      5. docker compose pull && up -d
      6. Wait for /api/health
      7. Open browser
#>

param(
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"
$ROOT = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Definition)
Set-Location $ROOT

function Write-Step {
    param([string]$Msg)
    Write-Host ""
    Write-Host "==> $Msg" -ForegroundColor Cyan
}

function Write-Ok    { param($M) Write-Host "  OK   $M" -ForegroundColor Green }
function Write-Warn  { param($M) Write-Host "  WARN $M" -ForegroundColor Yellow }
function Write-Err   { param($M) Write-Host "  ERR  $M" -ForegroundColor Red }

function Test-Cmd {
    param([string]$Name)
    return [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

function Read-Default {
    param([string]$Prompt, [string]$Default = "")
    $shown = if ($Default) { "$Prompt [$Default]: " } else { "$Prompt: " }
    $value = Read-Host $shown
    if ([string]::IsNullOrWhiteSpace($value)) { return $Default }
    return $value
}

function Read-Secret {
    param([string]$Prompt)
    $secure = Read-Host -AsSecureString -Prompt $Prompt
    $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try   { return [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr) }
    finally { [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }
}

# ---------- 1. Preflight ----------------------------------------------------
Write-Step "Checking prerequisites"

$missing = @()
if (-not (Test-Cmd "docker"))  { $missing += "Docker Desktop (https://www.docker.com/products/docker-desktop/)" }
if (-not (Test-Cmd "node"))    { $missing += "Node.js 20 LTS (https://nodejs.org/)" }
if (-not (Test-Cmd "claude"))  { $missing += "Claude Code CLI: npm install -g @anthropic-ai/claude-code" }

if ($missing.Count -gt 0) {
    Write-Err "Missing prerequisites:"
    $missing | ForEach-Object { Write-Host "    - $_" -ForegroundColor Yellow }
    Write-Host ""
    Write-Host "Install them and run this wizard again." -ForegroundColor Yellow
    exit 1
}

Write-Ok "Docker found"
Write-Ok "Node.js found"
Write-Ok "Claude Code CLI found"

# ---------- 2. Claude login -------------------------------------------------
Write-Step "Claude authentication"

$useSubscription = $true
$useSubAnswer = Read-Default "Use your Claude subscription instead of an API key? (y/n)" "y"
if ($useSubAnswer -match "^[Nn]") {
    $useSubscription = $false
}

$apiKey = ""
if ($useSubscription) {
    Write-Host "  Logging in via 'claude /login'. A browser will open."
    Write-Host "  After login completes, return to this window."
    Read-Host "  Press Enter to continue"
    & claude "/login"
    if ($LASTEXITCODE -ne 0) {
        Write-Warn "claude /login returned a non-zero status. Continuing — you can re-run later."
    } else {
        Write-Ok "Login completed"
    }
} else {
    $apiKey = Read-Secret "  Paste your ANTHROPIC_API_KEY (sk-ant-...)"
    if ([string]::IsNullOrWhiteSpace($apiKey)) {
        Write-Err "No key provided. Aborting."
        exit 1
    }
    Write-Ok "API key captured"
}

# ---------- 3. Adapter tokens (optional) -----------------------------------
Write-Step "Optional integrations"

$tgToken = Read-Default "  Telegram bot token (skip with Enter)"
$tgUsers = ""
if ($tgToken) {
    $tgUsers = Read-Default "  Allowed Telegram user IDs (comma-separated)"
}

$slackBot   = Read-Default "  Slack bot token (xoxb-..., skip with Enter)"
$slackSign  = ""
$slackApp   = ""
if ($slackBot) {
    $slackSign = Read-Default "  Slack signing secret"
    $slackApp  = Read-Default "  Slack app-level token (xapp-...)"
}

# ---------- 4. Generate .env -----------------------------------------------
Write-Step "Writing .env"

$sessionSecret = -join ((48..57) + (97..122) | Get-Random -Count 32 | ForEach-Object {[char]$_})

$envContent = @"
# Generated by Rogologo wizard on $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')
USE_SUBSCRIPTION=$($useSubscription.ToString().ToLower())
ANTHROPIC_API_KEY=$apiKey
DEFAULT_MODEL=claude-sonnet-4-6

TELEGRAM_BOT_TOKEN=$tgToken
TELEGRAM_ALLOWED_USERS=$tgUsers

SLACK_BOT_TOKEN=$slackBot
SLACK_SIGNING_SECRET=$slackSign
SLACK_APP_TOKEN=$slackApp

DATABASE_URL=sqlite+aiosqlite:///./data/rogologo.db
CORE_HOST=0.0.0.0
CORE_PORT=8000
DASHBOARD_HOST=0.0.0.0
DASHBOARD_PORT=3000
NEXT_PUBLIC_API_URL=http://localhost:8000

AGENTS_DIR=./agents
SKILLS_DIR=./skills
DISCOVERY_INTERVAL=5

MAX_CONCURRENT_RUNS=3

DEFAULT_LANG=en
ANT_FARM_ENABLED=true

TELEMETRY_ENABLED=false

SESSION_SECRET=$sessionSecret
"@

Set-Content -Path ".env" -Value $envContent -Encoding UTF8
Write-Ok ".env created"

# ---------- 4b. Seed templates --------------------------------------------
Write-Step "Seeding bundled agents and skills"
if (Test-Cmd "python") {
    & python ".\scripts\seed.py"
} elseif (Test-Cmd "py") {
    & py ".\scripts\seed.py"
} else {
    Write-Warn "Python not found; copy templates manually if you want demo agents."
}

# ---------- 5. Docker compose up ------------------------------------------
Write-Step "Building and starting Docker services"
& docker compose pull 2>&1 | Out-Null
& docker compose up -d --build
if ($LASTEXITCODE -ne 0) {
    Write-Err "docker compose up failed. Inspect output above and re-run."
    exit 1
}
Write-Ok "Containers are up"

# ---------- 6. Wait for health --------------------------------------------
Write-Step "Waiting for the core service to become healthy"
$deadline = (Get-Date).AddSeconds(120)
$healthy = $false
while ((Get-Date) -lt $deadline) {
    try {
        $r = Invoke-WebRequest -Uri "http://localhost:8000/api/health" -UseBasicParsing -TimeoutSec 2
        if ($r.StatusCode -eq 200) { $healthy = $true; break }
    } catch {}
    Start-Sleep -Seconds 2
}
if (-not $healthy) {
    Write-Warn "Core didn't become healthy in 120s. Check 'docker compose logs core'."
} else {
    Write-Ok "Core is healthy"
}

# ---------- 7. Open browser -----------------------------------------------
Write-Step "Opening dashboard"
Start-Process "http://localhost:3000"

Write-Host ""
Write-Host "==========================================" -ForegroundColor Green
Write-Host "  Installation complete." -ForegroundColor Green
Write-Host "  Dashboard: http://localhost:3000" -ForegroundColor Green
Write-Host "  API:       http://localhost:8000/docs" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green
Write-Host ""
